ALTER TABLE store	
	DROP PRIMARY KEY CASCADE;
ALTER TABLE product 
	DROP PRIMARY KEY CASCADE;
ALTER TABLE member
	DROP PRIMARY KEY CASCADE;
ALTER TABLE administrate
	DROP PRIMARY KEY CASCADE;
ALTER TABLE brand
 	  DROP PRIMARY KEY CASCADE;
ALTER TABLE youtuber
 	  DROP PRIMARY KEY CASCADE;
ALTER TABLE prefer_pro
  	 DROP PRIMARY KEY CASCADE;
ALTER TABLE video
   	DROP PRIMARY KEY CASCADE;
ALTER TABLE technic
   	DROP PRIMARY KEY CASCADE;
ALTER TABLE show
 	DROP PRIMARY KEY CASCADE;
ALTER TABLE buy
  	DROP PRIMARY KEY CASCADE;
ALTER TABLE review
	DROP PRIMARY KEY CASCADE;

DROP TABLE store;
DROP TABLE product;
DROP TABLE member;
DROP TABLE administrate;
DROP TABLE brand;
DROP TABLE youtuber;
DROP TABLE prefer_pro;
DROP TABLE video;
DROP TABLE technic;
DROP TABLE show;
DROP TABLE buy;
DROP TABLE review;

DROP SEQUENCE SEQ_PRO;
DROP SEQUENCE SEQ_MEM;
DROP SEQUENCE SEQ_STORE;
DROP SEQUENCE SEQ_brand;
DROP SEQUENCE SEQ_youtuber;
DROP SEQUENCE SEQ_prefer_pro;
DROP SEQUENCE SEQ_video;
DROP SEQUENCE SEQ_tec;
DROP SEQUENCE SEQ_buy;

DROP TABLE coupon CASCADE CONSTRAINTS; 
DROP TABLE saving CASCADE CONSTRAINTS; 
DROP TABLE comprise CASCADE CONSTRAINTS; 
DROP TABLE subscribe CASCADE CONSTRAINTS; 
DROP SEQUENCE seq_coupon;